# Your project's server will run on localhost:xxxx at this port
PORT: 1337

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"


# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
  - "src/assets/js/index.js"
  jsentrie: "src/assets/js/index.js"
  sassentrie: "src/assets/scss/main.scss"